data_list:
- /blue/bianjiang/cwang6/exposome/original/FoodAccessResearchAtlasData2015.xlsx
- /blue/bianjiang/cwang6/exposome/original/FoodAccessResearchAtlasData2019.xlsx
output_dir: /blue/bianjiang/cwang6/exposome/output/spacescan/
buffer_dir: /home/cwang6/exposome/data/original_data/ 
exposome_type: fara
